### ISSUE TITLE
Product 컴포넌트 개발

### ISSUE THREAD

**Issue by yungjurick** [dnd-mentee-4th/dnd-mentee-4th-7-frontend#3]
제품 컴포넌트 개발
- ProductListComponent
- ProductListItemComponent

ENUM
- PRODUCT_LIST_DIRECTION (VERTICAL, HORIZONTAL)

참고용 링크
https://www.notion.so/5b98414dd8d74e588ae55faea387dee1

**Comment by junho0956** [comment]
ProductListItemComponent부터 미리 만들어두겠습니다
